version: 2
jobs:
  build:
    working_directory: ~/buendia

    docker:
      - image: projectbuendia/debian-stretch:1.0.0

    steps:
      - checkout # check out the code in the project directory

      - restore_cache:
          keys:
              - buendia-v1-{{ .Branch }}-{{ .Revision }}
              - buendia-v1-{{ .Branch }}
              - buendia-v1-

      - run:
          name: Determine package version number
          command: |
              tools/get_package_version.sh > /tmp/buendia-version
          
      - run:
          name: Build all Debian packages
          command: make -C packages PACKAGE_VERSION=$(cat /tmp/buendia-version)

      - save_cache:
          key: buendia-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/.m2
            - /tmp/buendia-fetched

      - run:
          name: Collect and store test results
          # https://circleci.com/docs/2.0/collect-test-data/#maven-surefire-plugin-for-java-junit-results
          command: |
            mkdir -p /tmp/artifacts/tests/junit
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} /tmp/artifacts/tests/junit/ \;
          when: always

      - store_test_results:
          path: /tmp/artifacts/tests
             
      - run: 
          name: Collect and store built packages
          command: mkdir -p /tmp/artifacts/packages && cp $(find packages -name '*.deb') /tmp/artifacts/packages

      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  normal-build:
    jobs:
      - build
